import { defineConfig } from 'oxlint';

export default defineConfig({
  ignorePatterns: [
    'dist/**',
    'storybook-static/**',
    'coverage/**',
    '.vitest-attachments/**',
    'src/app/__screenshots__/**',
  ],
  plugins: ['eslint', 'typescript', 'unicorn', 'oxc', 'import', 'jsdoc', 'promise', 'vitest'],
  categories: {
    correctness: 'error',
    suspicious: 'error',
    pedantic: 'error',
    perf: 'error',
    style: 'error',
    restriction: 'error',
    nursery: 'error',
  },
  rules: {
    'no-unused-vars': 'error',
    'sort-keys': 'off',
    'no-shadow': 'off',
    'max-lines-per-function': 'off',
    'no-undefined': 'off',
    'no-magic-numbers': 'off',
    'no-console': 'off',
    'new-cap': 'off',
    'sort-imports': 'off',
    'no-duplicate-imports': 'off',
    'no-inline-comments': 'off',
    'no-undef': 'off',
    'no-underscore-dangle': 'off',
    'id-length': 'off',
    'func-style': ['warn', 'declaration', { allowArrowFunctions: true }],
    'max-statements': 'off',
    'capitalized-comments': 'off',
    'default-case': 'off',
    'guard-for-in': 'off',
    'no-use-before-define': 'off',
    'no-ternary': 'off',
    'no-void': 'off',
    'max-params': 'off',
    'max-lines': 'off',
    'no-warning-comments': 'off',
    'no-continue': 'off',
    'require-unicode-regexp': 'off',
    'prefer-destructuring': 'off',
    'prefer-object-has-own': 'off',
    'import/no-unassigned-import': 'off',
    'import/consistent-type-specifier-style': 'off',
    'jsdoc/require-param': 'off',
    'jsdoc/require-returns': 'off',
    'typescript/ban-types': 'off',
    'typescript/consistent-type-definitions': 'off',
    'typescript/consistent-type-imports': 'off',
    'typescript/explicit-function-return-type': 'off',
    'typescript/explicit-member-accessibility': 'off',
    'typescript/explicit-module-boundary-types': 'off',
    'typescript/method-signature-style': 'off',
    'typescript/no-empty-object-type': 'off',
    'typescript/no-non-null-assertion': 'off',
    'unicorn/filename-case': [
      'error',
      {
        cases: {
          kebabCase: true,
          pascalCase: true,
          camelCase: true,
        },
      },
    ],
    'unicorn/no-null': 'off',
    'unicorn/no-array-callback-reference': 'off',
    'unicorn/no-array-reduce': 'off',
    'unicorn/consistent-function-scoping': 'off',
    'unicorn/no-useless-undefined': 'off',
    'unicorn/number-literal-case': 'off',
    'unicorn/numeric-separators-style': 'off',
    'unicorn/prefer-at': 'off',
    'unicorn/prefer-native-coercion-functions': 'off',
    'oxc/no-optional-chaining': 'off',
    'oxc/no-async-await': 'off',
    'oxc/no-rest-spread-properties': 'off',
    'import/default': 'off',
    'import/group-exports': 'off',
    'import/no-default-export': 'off',
    'import/no-named-export': 'off',
    'import/prefer-default-export': 'off',
    'import/exports-last': 'off',
    'import/no-relative-parent-imports': 'off',
    'promise/prefer-await-to-then': 'off',
    'vitest/consistent-test-it': 'off',
    'vitest/expect-expect': 'off',
    'vitest/no-hooks': 'off',
    'vitest/no-importing-vitest-globals': 'off',
    'vitest/prefer-lowercase-title': 'off',
    'vitest/prefer-describe-function-title': 'off',
    'vitest/prefer-expect-assertions': 'off',
    'vitest/prefer-mock-return-shorthand': 'off',
    'vitest/prefer-strict-equal': 'off',
    'vitest/prefer-to-be-falsy': 'off',
    'vitest/require-hook': 'off',
    'vitest/require-test-timeout': 'off',
    'vitest/require-top-level-describe': 'off',
  },
});
